### ISSUE TITLE
address.Parse bug?

### ISSUE THREAD

**Issue by ygcool** [nervosnetwork/ckb-sdk-go#102]
ckb-sdk-go version：v0.101.1

```
addr, _ := address.Parse("ckb1qyqdp9y8muqy5tv9vks448nkag22utyj43vs2rwgz5")
fmt.Println(addr.Mode)
```

cmd:
![image](https://user-images.githubusercontent.com/16422689/144369964-8d3a30e8-4e8b-4d2b-bf35-c858faef4c4d.png)

Why is there a number being printed?

**Comment by ygcool** [comment]
ckb-sdk-go version：v0.101.1

**Comment by fjchen7** [comment]
Hi @ygcool, yeah that is an oversight that a number is print in parsing process. But you still can feel free to check `mode`'s value which will be `ckb` (stand for mainnet`) in your case. For example, 

```go
addr, _ := address.Parse("ckb1qyqdp9y8muqy5tv9vks448nkag22utyj43vs2rwgz5")
if addr.Mode == Mainnet {
    fmt.Println("This is mainnet address")
}
```

Thank you for reporting this unexpected behaviour at parsing address.

**Comment by ygcool** [comment]
ok, thanks!
