### ISSUE TITLE
address.GenerateFullPayloadAddress deprecated

### ISSUE THREAD

**Issue by x777** [nervosnetwork/ckb-sdk-go#104]
```
       // Generate private key
	keyString, err := internalUtils.GeneratePrivateKey(32)
	if err != nil {
		return "", "", err
	}

	systemScripts, _ := utils.NewSystemScripts(client)

	key, err := secp256k1.HexToKey(keyString)
	if err != nil {
		return "", "", err
	}

	lock, _ := key.Script(systemScripts)
	addr, _ := address.GenerateFullPayloadAddress(address.FullTypeFormat, network, lock)
```

What method I should change my logic to?

**Comment by x777** [comment]
By `GenerateBech32mFullAddress()`?

**Comment by fjchen7** [comment]
@x777 Yes, use `GenerateBech32mFullAddress`.

**Comment by x777** [comment]
Can you please ask somebody to update faucet service to support address for such format?

I tried to generate this new method address, but faucet say that this address not valid:
`ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqt0kkpq6akwcnmpqzcdrql5uz6fgtnqnrgqme4tg`

But with blockchain it works fine.

**Comment by fjchen7** [comment]
Sorry for delay reply. Using this method to convert it to short address, and then use it to get token from faucet.

```go
shortAddress, err := ConvertToShortAddress("ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqt0kkpq6akwcnmpqzcdrql5uz6fgtnqnrgqme4tg")
```
