### ISSUE TITLE
Error HexToKey Error: invalid hex string with GenerateBech32mFullAddress()

### ISSUE THREAD

**Issue by x777** [nervosnetwork/ckb-sdk-go#105]
Previously, when I used address.GenerateFullPayloadAddress and to get key to sign transaction, I had following code from "github.com/nervosnetwork/ckb-sdk-go/crypto/secp256k1" package:

```
key, err := secp256k1.HexToKey(privateKey)
	if err != nil {
		fmt.Println("HexToKey Error:", err)
		return nil, err
	}

// 2. sign the tx
	err = transaction.SingleSegmentSignTransaction(ckbTx, 0, len(ckbTx.Witnesses), transaction.EmptyWitnessArg, key)
	if err != nil {
		fmt.Println("Single Segment Sign Transaction Error:", err)
		return nil, err
	}

```

Now, using GenerateBech32mFullAddress() method:

```
address, _ := address.GenerateBech32mFullAddress(network)
return address.Address, address.PrivateKey, nil
```

I got error: `Error HexToKey Error: invalid hex string`

What now should I use to get key private for address?

**Comment by fjchen7** [comment]
The `address.PrivateKey` has `0x` as prefix, which is not allowed by `secp256k1.HexToKey`. Try this code snippet

```go
addr, _ := GenerateBech32mFullAddress(Mainnet)
// get rid of prefix 0x
key, err := secp256k1.HexToKey(addr.PrivateKey[2:])
if err != nil {
    fmt.Println("HexToKey Error:", err)
    return nil, err
}
```

**Comment by x777** [comment]
Yes, solution: Problem was in "0x" at beginning of key string. In previous version key started without it. But I can be wrong. Thanks anyway!
