### ISSUE TITLE
mercury - GetTransactionInfo err

### ISSUE THREAD

**Issue by ygcool** [nervosnetwork/ckb-sdk-go#108]
ckb-sdk-go version: v0.101.2
txHash : 0x028304f1995a50d5c11c5bfe8338535243a7b896014fa7c64da75a47ef7b4a24

```
apic, _ := mercury.Dial(“https://mercury-mainnet.ckbapp.dev”)
apic.GetTransactionInfo("0x028304f1995a50d5c11c5bfe8338535243a7b896014fa7c64da75a47ef7b4a24")
```

err:
![image](https://user-images.githubusercontent.com/16422689/145510028-749b086a-2f4c-4e7c-b7dc-4d0b72e44f63.png)

**Comment by fjchen7** [comment]
This is an unexpected unmarshal error. Will fix it and release a new version next week.

BTW, any other problems or advice during using go SDK?

**Comment by ygcool** [comment]
I hope there will be better examples to help newcomers use, such as multi-signature transfer, etc.
