### ISSUE TITLE
Unmarshal error in QueryTransactionsWithTransactionInfo

### ISSUE THREAD

**Issue by opera-andreasl** [nervosnetwork/ckb-sdk-go#159]
Calling `QueryTransactionsWithTransactionInfo` yields an error for certain transactions.

Test case to reproduce the issue
```golang
func Test_faultyTransactionInfo(t *testing.T) {
	addr := "ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqvs0y84eqdt26nqx9g6l6cc6vqm5gy4kdsnfug9h"
	item, _ := model.NewIdentityItemByAddress(addr)

	payload := &model.QueryTransactionsPayload{
		Item:       item,
		AssetInfos: []*model.AssetInfo{model.NewCkbAsset()},
		Pagination: &model.PaginationRequest{
			Order:       model.OrderDesc,
			Limit:       50,
			ReturnCount: false,
		},
	}

	c, _ := mercury.Dial("https://mercury-mainnet.ckbapp.dev/0.4")
	_, err := c.QueryTransactionsWithTransactionInfo(payload)
	if err != nil {
		t.Error(err)
	}
}
```

Error: `json: cannot unmarshal string into Go struct field TransactionInfoWrapper.response.value of type uint64`
Version: v2.0.1

**Comment by fjchen7** [comment]
The JSON marshall is missing for the struct `DaoInfo`. Thanks for reporting. 

If you are working on integration with ckb-sdk-go, we recommend you adopt the next upcoming version that finalizes the APIs. We will release it soon.
