### ISSUE TITLE
Filter out used live cells in collector

### ISSUE THREAD

**Issue by fjchen7** [nervosnetwork/ckb-sdk-go#172]
When using ckb/indexer/light client to collect live cells and construct transactions, If transactions can't be confirmed in time due to network congestion or the user collects live cells and builds transactions concurrently, it may happen that more than two transactions use the same live cells and are sent to networks. As a result, only one will be accepted and the others will be rejected all, which brings bad experiences to users.

We need to implement a buffer to record the live cells that are used but may not be consumed by the network. When collecting new live cells, we have to filter out those that are in this buffer. Also, we need to have a algorithms to move cells out of this buffer for avoiding too much memory usage,

**Comment by quake** [comment]
close via https://github.com/nervosnetwork/ckb-sdk-go/pull/177
