### ISSUE TITLE
get transaction rpc unmarshal error

### ISSUE THREAD

**Issue by shaojunda** [nervosnetwork/ckb-sdk-go#175]
## Bug Report

Encountered error ` json: cannot unmarshal non-string into Go struct field TxStatus.tx_status.block_hash of type types.Hash` while getting a rejected transaction through RPC `GetTransaction`

tx_hash: [0xb2b8911aeac92de53fc3edc218cf979ae4752a7a67e698b0b1726db53126f31f](https://pudge.explorer.nervos.org/transaction/0xb2b8911aeac92de53fc3edc218cf979ae4752a7a67e698b0b1726db53126f31f)

calling RPC directly through the node can return normally.

```
{"jsonrpc":"2.0","result":{"transaction":null,"tx_status":{"block_hash":null,"reason":"{\"type\":\"Resolve\",\"description\":\"Resolve failed Dead(OutPoint(0xb64253fca9a6fa060f5cd3e16cfd8a618c7d2e3aa3aa9a6d190d79fc405ac64f00000000))\"}","status":"rejected"}},"id":42}
```

### Environment

- **CKB version**: 0.105.1
- **ckb-sdk-go version**: v2.0.2
- **Chain**: testnet
- **Operating system**: Ubuntu 20.04
- **Arch**: x64

**Comment by fjchen7** [comment]
This problem has already been fixed in develop branch but not released yet. Thanks for reporting and we will add more test cases for usability.

**Comment by code-monad** [comment]
This issue was fixed previously and got some update in the recent release. please check  https://github.com/nervosnetwork/ckb-sdk-go/releases/tag/v2.1.0
