### ISSUE TITLE
question about send chained transaction

### ISSUE THREAD

**Issue by shaojunda** [nervosnetwork/ckb-sdk-go#191]
https://github.com/nervosnetwork/ckb-sdk-go/blob/v2/collector/offchain_input_iterator.go#L59

If there is only one element in the `offChainLiveCells`, will this element not be used?

**Comment by code-monad** [comment]
According to the code implementation, this do will make the only head element skip the process.
comparing to [`ckb-java-sdk`'s code](https://github.com/nervosnetwork/ckb-sdk-java/blob/c9fb5cc8a853c9a41b42d02e56f4d2a8d7fbdab9/ckb/src/main/java/org/nervos/ckb/transaction/OffChainInputIterator.java#L101). the initialized iterator is not equivalent with go's `List.Front()`, this  is an ill-formed code, **considered as a bug.**

**Comment by code-monad** [comment]
will fix by  #193
