### ISSUE TITLE
The get_block/get_lock_by_number rpc method does not support passing parameters verbosity/with_cycles

### ISSUE THREAD

**Issue by 15168316096** [nervosnetwork/ckb-sdk-go#197]
Version：V2.1.1
Script：The get_block/get_lock_by_number rpc method does not support passing parameters verbosity/with_cycles
ScreenShot：
![image](https://user-images.githubusercontent.com/45781590/212630105-70467f03-6415-4e42-8fea-e7e1b9c2cec4.png)
![image](https://user-images.githubusercontent.com/45781590/212630624-815e74c0-3426-4a38-a2a1-a2e49818c3d2.png)

**Comment by code-monad** [comment]
fixed by #200
