### ISSUE TITLE
transaction builder

### ISSUE THREAD

**Issue by x777** [nervosnetwork/ckb-sdk-go#91]
Hi, I see in code some transaction builder that is used for Payment. Can we use it to build simple transactions? Thx!

**Comment by x777** [comment]
> Are you trying to call `build_simple_transactions` provided by [Mercury](https://github.com/nervosnetwork/mercury) via ckb-sdk-go. If so, you can use `BuildSimpleTransferTransaction` defined in `mercury/client.go`.
> 
> You can also use util methods in `utils` and `transaction` to build transaction by manual?

I see that it's not Mercury.  This one I mean - https://github.com/nervosnetwork/ckb-sdk-go/tree/develop/transaction/builder
Do you have some examples of using it? I got some strange error. Not sure if I am using it in right way.

**Comment by fjchen7** [comment]
> > Are you trying to call `build_simple_transactions` provided by [Mercury](https://github.com/nervosnetwork/mercury) via ckb-sdk-go. If so, you can use `BuildSimpleTransferTransaction` defined in `mercury/client.go`.
> > You can also use util methods in `utils` and `transaction` to build transaction by manual?
> 
> I see that it's not Mercury. This one I mean - [`develop`/transaction/builder](https://github.com/nervosnetwork/ckb-sdk-go/tree/develop/transaction/builder?rgh-link-date=2021-11-16T13%3A37%3A43Z) Do you have some examples of using it? I got some strange error. Not sure if I am using it in right way.

Can you post your code here? It could help us pinpoint the exact issue.

**Comment by x777** [comment]
> > > Are you trying to call `build_simple_transactions` provided by [Mercury](https://github.com/nervosnetwork/mercury) via ckb-sdk-go. If so, you can use `BuildSimpleTransferTransaction` defined in `mercury/client.go`.
> > > You can also use util methods in `utils` and `transaction` to build transaction by manual?
> > 
> > 
> > I see that it's not Mercury. This one I mean - [`develop`/transaction/builder](https://github.com/nervosnetwork/ckb-sdk-go/tree/develop/transaction/builder?rgh-link-date=2021-11-16T13%3A37%3A43Z) Do you have some examples of using it? I got some strange error. Not sure if I am using it in right way.
> 
> Can you post your code and shows what error you met here? It could help us pinpoint the exact issue.

This is what I tried to get from Payment package and `generateTxWithIndexer()` function:

```
func build(from, to string, amount, feeRate uint64) (*types.Transaction, error) {
	fromAddress, err := address.Parse(from)
	if err != nil {
		return nil, fmt.Errorf("parse from address %s error: %v", from, err)
	}
	toAddress, err := address.Parse(to)
	if err != nil {
		return nil, fmt.Errorf("parse to address %s error: %v", to, err)
	}

	if fromAddress.Mode != toAddress.Mode {
		return nil, fmt.Errorf("from address and to address with diffrent network: %v:%v", fromAddress.Mode, toAddress.Mode)
	}

	director := builder.Director{}

	txBuilder := &builder.CkbTransferUnsignedTxBuilder{
		To:               fromAddress.Script,
		From:             toAddress.Script,
		TransferCapacity: amount,
		FeeRate:          feeRate,
	}

	director.SetBuilder(txBuilder)

	tx, _, err := director.Generate()
	if err != nil {
		return nil, err
	}
	return tx, err
}

```

Or if you have practice example would be cool, because using Payment package looks like create every time new cell, and it's not good for transferring in my case.

**Comment by fjchen7** [comment]
Hi @x777 

You do not specify the live cells (UTXO in CKB) you are going to spend in the your code.  In `generateTxWithIndexer()` these live cells are collected by CKB-indexer. You can find these data in https://explorer.nervos.org/ and construct live cells by manual, but this must be a tedious work. So using CKB-indexer is a more recommended way.

You can use the public indexer node https://testnet.ckb.dev/indexer or https://mainnet.ckb.dev/indexer.

**Comment by x777** [comment]
> Hi @x777
> 
> You do not specify the live cells (UTXO in CKB) you are going to spend in the your code. In `generateTxWithIndexer()` these live cells are collected by CKB-indexer. You can also find these data in https://explorer.nervos.org/ and construct live cells by manual, but this must be a tedious work. So using CKB-indexer is a more recommended way.
> 
> You can use the public indexer node https://testnet.ckb.dev/indexer or https://mainnet.ckb.dev/indexer.

Yes, I saw this moment. What I really can't understand and that's why I didn't use collector from  `generateTxWithIndexer` because every Payment additional creates a new cell (+61 CKB) and as a result, I can't see the right balance. What best approach to avoid this or it's impossible by the blockchain model? 

The main reason why I am using `Payment` for transfer is because `Single input send transaction` example really hard to implement. If you have some additional real practice examples would be great. Thanks!

**Comment by x777** [comment]
@fjchen7 can you provide examples?

**Comment by fjchen7** [comment]
Hi @x777 Let's clarify the requirement first. What you want to do right now is to send CKB from your secp256 address to another secp256 address, and not other logic involved, right?

**Comment by x777** [comment]
> Hi @x777 Let's clarify the requirement first. What you want to do right now is to send CKB from your secp256 address to another secp256 address, and not other logic involved, right?

Yes, especially clear examples for situations when need create a new cell and when no. Another word - best practice for newbies. I could make some posts for the community with them if you give me a clear understanding. Let's make Go SDK also so popular and useful like JS)

**Comment by fjchen7** [comment]
Hi @x77,

If you want to send CKB without CKB-indexer or Mercury involved, please refer to [README.md](https://github.com/nervosnetwork/ckb-sdk-go#sign-and-send-transaction). I think this is the most concise example in this case, but you need to find cell/tx data by yourself ([CKB explorer](https://explorer.nervos.org/aggron/) is a good tool).

If you have CKB-indexer, then `generateTxWithIndexer` method in payment package is a good choice. I think the `	builder.CkbTransferUnsignedTxBuilder` provided is enough for your case and you don't need to implement your own builder.

If you have Mercury, check the `build_simple_transfer_transaction_example.go#TestSourceByClaimable`. It call Mercury [build_simple_transfer_transaction](https://github.com/nervosnetwork/mercury/blob/dev/core/rpc/README.md#method-build_simple_transfer_transaction) and the only thing you need to do is sign.

All above will create a new cell for receiver address. They are all cases for secp256 address.

If you don't like it that each transaction will create one more cell for receiver address, then you need to make sure receiver address has at least one live [acp cell](https://talk.nervos.org/t/rfc-anyone-can-pay-lock/4438). You can understand acp is another kind of address compared with secp256 address. Acp cell can be used as input cell by anyone if you don't reduce its ckb (capacity), and if you consume a acp cell then you need to create a new one. So using acp cell as input in transaction won't create more cells for receiver. For this case, unfortunately there is not a good method in ckb-sdk-go.

ckb-sdk-go is not in a good quality. We are planning to refactor it.

I recommend you join our [discord](https://discord.gg/AqGTUE9), and you can get technical support more timely

**Comment by x777** [comment]
> I recommend you join our [discord](https://discord.gg/AqGTUE9), and you can get technical support more timely

I am an active member here already, but Golang isn't popular, because I switched to Github.


> If you don't like it that each transaction will create one more cell for receiver address, then you need to make sure receiver address has at least one live [acp cell](https://talk.nervos.org/t/rfc-anyone-can-pay-lock/4438). You can understand acp is another kind of address compared with secp256 address. Acp cell can be used as input cell by anyone if you don't reduce its ckb (capacity), and if you consume a acp cell then you need to create a new one. So using acp cell as input in transaction won't create more cells for receiver. For this case, unfortunately there is not a good method in ckb-sdk-go.

This is what I am looking for "best practice". Can I send ALL capacity from the address instead?


> ckb-sdk-go is not in a good quality. We are planning to refactor it.

And would be good to add additional comments there.

**Comment by fjchen7** [comment]
> This is what I am looking for "best practice". Can I send ALL capacity from the address instead?

What do you mean by "send ALL capacity from the address"? From who to whom? You have to find **all** live cells as input if you want to send all capacity from a certain address.

> And would be good to add additional comments there.

For my perspective, ckb-sdk-go does not have a good abstraction and user-friendly interface. So think twice if you want to use it in production environment. Just my opinion.

**Comment by x777** [comment]
> For my perspective, ckb-sdk-go does not have a good abstraction and user-friendly interface. So think twice if you want to use it in production environment. Just my opinion.

Honestly hard to understand such words from the dev of the project. Anyway, I understood that it was a bad idea to start to develop this SDK and to use it. Better one completed SDK and ready for real projects than few not useful. Such way is not good for successfully growing the ecosystem. Just my opinion.
