### ISSUE TITLE
v0.101.0-beta.2 release

### ISSUE THREAD

**Issue by x777** [nervosnetwork/ckb-sdk-go#94]
Looks like v0.101.0-beta.1 code with Mercury isn't working without updating to v0.101.0-beta.2. What version with Mercury support is stable now or is it's a bad idea to use it for production? Advice, please. Thx!

**Comment by fjchen7** [comment]
ckb-sdk-go v0.101.0-beta.1 contains several breaking changes including RPC request and response structure changes, and can only work with Mercury [v0.2.0-beta.4)](https://github.com/nervosnetwork/mercury/releases/tag/v0.2.0-beta.4). 

Ckb-sdk-go is still far from stable, and for now I don't suggest using it for production.

**Comment by x777** [comment]
For a few months, I used` v0.43.2`  without problems, but I didn't use Mercury.
