### ISSUE TITLE
create transaction error: collect cell error: stream error: stream ID 9; INTERNAL_ERROR

### ISSUE THREAD

**Issue by x777** [nervosnetwork/ckb-sdk-go#99]
Error:
`create transaction error: collect cell error: stream error: stream ID 9; INTERNAL_ERROR`
`collect cell error: stream error: stream ID 9; INTERNAL_ERROR`

Code:
```
key, err := secp256k1.HexToKey(privateKey)
	if err != nil {
		log.Printf("import private key error: %v\n", err)
		return err
	}

	pay, err := payment.NewPayment(from_addr, to_addr, amount*100000000, 1100)
	if err != nil {
		log.Printf("create payment error: %v\n", err)
		return err
	}
	systemScripts, _ := utils.NewSystemScripts(client)
	_, err = pay.GenerateTx(client, systemScripts)
	if err != nil {
		log.Printf("create transaction error: %v\n", err)
		return err
	}

	_, err = pay.Sign(key)
	if err != nil {
		log.Printf("sign transaction error: %v\n", err)
		return err
	}

	hash, err := pay.Send(client)
	if err != nil {
		fmt.Printf("send transaction error: %v\n", err)
		return err
	}
```

**Comment by fjchen7** [comment]
Hi @x777, is seems that this error is returned by ckb-indexer. Do you have a healthy ckb-indexer?

**Comment by x777** [comment]
> Hi @x777, it seems that this error is returned by ckb-indexer. Do you have a healthy ckb-indexer?

It's testnet https://testnet.ckbapp.dev/indexer and it's working good mostly time, maybe was some temporary error. 
Hope, with mainet will work fine. Thanks!
